language: cpp

dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get install -y libboost-all-dev

  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:jonathonf/binutils; fi

  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then sudo apt install g++-7 binutils; fi

script:
  - cd test
  - make clean ; CXX=g++ make && make test
  - make clean ; CXX=g++-7 make with_sanitizers && make test
  - make clean ; CXX=g++-7 make build17 && make test
